import assert from "node:assert/strict";
import { copyFile, mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";
import { openJournalSession } from "../dist/flow-control/journal-storage.js";
import { createPiLedgerStore } from "../dist/flow-control/pi-ledger-store.js";
import { FlowReceiptLedger } from "../dist/flow-control/receipt-ledger.js";
import { BACKGROUND_CONTEXT, value } from "../dist/flow-control/scalar-storage.js";

const scope = { sessionId: "fixture-session", branchId: "fixture-branch" };
// Generated by Pi 0.99.2 and the flow receipt store, including single- and multi-write transactions.
const fixture = new URL("./fixtures/flow-journal-pi-0.99.2.jsonl", import.meta.url);

test("a Pi 0.99.2 journal preserves receipt bytes and handoff uncertainty in the owned storage adapter", async (t) => {
	const root = await mkdtemp(join(tmpdir(), "jouzu-flow-compat-"));
	const path = join(root, "flow.jsonl");
	let session;
	t.after(async () => {
		await session?.close(BACKGROUND_CONTEXT);
		await rm(root, { recursive: true, force: true });
	});
	const original = await readFile(fixture, "utf8");
	await copyFile(fixture, path);
	session = await openJournalSession(path);
	assert.equal(await readFile(path, "utf8"), original);
	const before = (await session.getValue(value("jouzu.flow.attempt", "attempt"), BACKGROUND_CONTEXT)).value;
	assert.equal(before.phase, "handed-off");
	assert.equal(before.requests[0].handedOff, true);
	const ledger = await FlowReceiptLedger.attach(createPiLedgerStore(session), scope);
	const state = await ledger.snapshot();
	assert.equal(state.generation, 2);
	assert.equal(state.activeAttemptId, undefined);
	assert.equal(state.attempts[0].phase, "uncertain");
	assert.deepEqual(state.attempts[0].members, before.members);
	assert.deepEqual(state.attempts[0].history, before.history);
	assert.deepEqual(state.attempts[0].requests, before.requests);
	await session.close(BACKGROUND_CONTEXT);
	const appended = await readFile(path, "utf8");
	assert.ok(appended.startsWith(original), "normal commits append without rewriting existing receipts");
	const writes = appended
		.trimEnd()
		.split("\n")
		.slice(1)
		.flatMap((line) => {
			const record = JSON.parse(line);
			return Array.isArray(record) ? record : [record];
		});
	for (let index = 1; index < writes.length; index++) assert.ok(writes[index].seq > writes[index - 1].seq);
	assert.ok(writes.at(-1).seq > 13);
	session = await openJournalSession(path);
	const reopened = await FlowReceiptLedger.attach(createPiLedgerStore(session), scope);
	const next = (await reopened.snapshot()).attempts[0];
	assert.equal(next.phase, "uncertain");
	assert.equal(next.requests[0].handedOff, true);
	assert.deepEqual(next.members, before.members);
	assert.deepEqual(next.history, before.history);
});
